name: deploy ipl

on:
  push:
    branches: [ master, develop, feature/** ]

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: 1. Setup GCP Service Account
        uses: google-github-actions/auth@v2
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        uses: docker/login-action@v2
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Build
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ipl:latest .
      - name: Push
        run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ipl/ipl:latest
      - name: 3. Deploy
        run: |
          gcloud run deploy serverless-app \
          --region asia-south1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/ipl \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}
